name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main ]
  workflow_dispatch:

jobs:
  quality:
    uses: prinsfrank/CI-PHP/.github/workflows/quality.yml@main
    with:
      PHP_VERSION: '8.3'
      PHP_VERSIONS: '["8.2", "8.3", "8.4", "8.5"]'
    secrets: inherit
